### ISSUE TITLE
ClassCast exception from dataToSketch

### ISSUE THREAD

**Issue by will-lauer** [DataSketches/sketches-hive#8]
When running a query in hive that includes `... estimate_sketch(data_to_sketch(column)) ...`, I get a class cast error with the stack trace of:

```
Caused by: java.lang.ClassCastException: org.apache.hadoop.hive.serde2.lazy.LazyString cannot be cast to org.apache.hadoop.io.Text
        at org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableStringObjectInspector.getPrimitiveJavaObject(WritableStringObjectInspector.java:46)
        at org.apache.hadoop.hive.serde2.objectinspector.primitive.PrimitiveObjectInspectorUtils.getString(PrimitiveObjectInspectorUtils.java:843)
        at com.yahoo.sketches.hive.theta.DataToSketchUDAF$DataToSketchEvaluator.updateData(DataToSketchUDAF.java:459)
        at com.yahoo.sketches.hive.theta.DataToSketchUDAF$DataToSketchEvaluator.iterate(DataToSketchUDAF.java:241)
        at org.apache.hadoop.hive.ql.udf.generic.GenericUDAFEvaluator.aggregate(GenericUDAFEvaluator.java:185)
        at org.apache.hadoop.hive.ql.exec.GroupByOperator.updateAggregations(GroupByOperator.java:612)
        at org.apache.hadoop.hive.ql.exec.GroupByOperator.processHashAggr(GroupByOperator.java:787)
        at org.apache.hadoop.hive.ql.exec.GroupByOperator.processKey(GroupByOperator.java:693)
        at org.apache.hadoop.hive.ql.exec.GroupByOperator.process(GroupByOperator.java:761)
```

This is occuring with hive Hive 1.2.1.5.1601270058

**Comment by will-lauer** [comment]
tweaking the query to use `... estimate_sketch(data_to_sketch(lower(column))) ...` seems to work around the problem.

**Comment by leerho** [comment]
It is good that we documented this, but it is clearly outside the scope of what the sketches-core can do anything about.  The above "solution" doesn't say whether there is anything that needs to be fixed in sketches-hive either.  So I'm going to close this for now.
